# The Data Source Name for the database
# Make sure you override this in production with the environment variable: RESTFUL_DSN
# dsn: "postgres://postgres:docker@127.0.0.1:5432/go_restful?sslmode=disable"
dsn: RESTFUL_DSN

# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   RESTFUL_JWT_VERIFICATION_KEY
#   RESTFUL_JWT_SIGNING_KEY
jwt_verification_key: RESTFUL_JWT_VERIFICATION_KEY
jwt_signing_key: RESTFUL_JWT_SIGNING_KEY
# Uncomment the following line and set an appropriate JWT signing method, if needed
# The default signing method is HS256.
#jwt_signing_method: "HS256"

firebase_credentials_json: RESTFUL_FIREBASE_CREDENTIALS_JSON